sudo: required
services:
  - docker

before_install:
  - docker build -t shoheihosaka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shoheihosaka/react-test npm test

after_success:
  - docker build -t shoheihosaka/udemy-complex-client ./client
  - docker build -t shoheihosaka/udemy-complex-nginx ./nginx
  - docker build -t shoheihosaka/udemy-complex-server ./server
  - docker build -t shoheihosaka/udemy-complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKR_ID" --password-stdinb
  #  Take those image and push them to docker hub
  - docker push shoheihosaka/udemy-complex-client
  - docker push shoheihosaka/udemy-complex-nginx
  - docker push shoheihosaka/udemy-complex-server
  - docker push shoheihosaka/udemy-complex-worker

  deploy:
    provider: elasticbeanstalk
    region: ap-northeast-1
    app: udemy-docker-complex
    env: UdemyDockerComplex-env
    bucket-name: elasticbeanstalk-ap-northeast-1-064720504409
    bucket-path: UdemyDockerComplex
    on:
      branch: maseter
    accesskey: XXXX
    secretkey: