sudo: required
services:
  - docker

before_install:
  - docker build -t shoheihosaka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shoheihosaka/react-test npm test

after_success:
  - docker build -t shoheihosaka/udemy-complex-client ./client
  - docker build -t shoheihosaka/udemy-complex-nginx ./nginx
  - docker build -t shoheihosaka/udemy-complex-server ./server
  - docker build -t shoheihosaka/udemy-complex-worker ./worker
  # Log in to the docker CLI

  #  Take those image and push them to docker hub
  